import Head from "next/head";
import Image from "next/image";
import {MainWrapperDiv} from "./../components/MainResponsive/MainWrapperBox";
import {HeaderMain} from "./../components/Header/HeaderMain";

export default function Home() {
  return (
    <MainWrapperDiv>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'></meta>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='row-start-1 sm:col-start-1 sm:col-end-2 md:col-start-2 md:col-end-6 xl:col-start-2 xl:col-span-8 h-auto bg-red-200'>
        <HeaderMain />
      </div>
      <div className='row-start-2 sm:col-start-1 sm:col-end-2 md:col-start-1 md:col-span-6 xl:col-span-12 h-96 bg-red-200'></div>
      <div className='row-start-3 sm:col-start-1 sm:col-end-2 md:col-start-2 md:col-end-6 xl:col-start-2 xl:col-span-8 h-96 bg-red-200'></div>
    </MainWrapperDiv>
  );
}
