import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import {MainWrapperDiv} from "./../components/MainResponsive/MainWrapperBox";
import {HeaderMain} from "./../components/Header/HeaderMain";
import Header from "../components/Elements/GridItem";
import Main from "../components/Elements/GridItem";
import Footer from "../components/Elements/GridItem";
import Card1 from "./../components/Cards/Card1";
import ItemSplitter from "../components/Elements/GridItem";
import {Card2} from "./../components/Cards/Card2";
import {Card3} from "./../components/Cards/Card3";
import {CardProduct} from "./../components/Cards/CardProduct";
import {CardProduct2} from "./../components/Cards/CardProduct2";
import {CardVideo} from "../components/Cards/CardVideo";

export default function Home({top, mid, bottom}) {
  return (
    <MainWrapperDiv>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'></meta>
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Mansalva&family=Rajdhani:wght@600&family=Roboto&display=swap'
          rel='stylesheet'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header classes='header_default_div'>
        <HeaderMain />
      </Header>
      <Main classes='main_default_style'>
        {/* <CardVideo video_default='w-full mb-4' /> */}
        <Card3
          text_wrapper='relative text-center -top-16'
          text_bg='bg-pink'
          img_url={"/fg1.webp"}
        />

        <ItemSplitter classes='grid_item_splitter_default4'>
          {top &&
            top.map((el) => (
              <CardProduct2
                key={el.title}
                link_url='/category/women'
                text_title={el.title.toUpperCase()}
                text_price={el.price + "" + "$"}
                text_category={el.category.toUpperCase()}
                text_size='text-base'
                priority={true}
              />
            ))}

          {/* <CardProduct2
            link_url='/category/men'
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
            priority={true}
          />
          <CardProduct2
            link_url='/category/men'
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
            priority={true}
          />
          <CardProduct2
            link_url='/category/men'
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
            priority={true} />*/}
        </ItemSplitter>
        {/* <ItemSplitter classes='grid_item_splitter_default4'>
          <Card1
            link_url='/category/1'
            text='SUMMER VIBES'
            img_url={"/f4.webp"}
          />
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
        </ItemSplitter> */}

        <ItemSplitter classes='grid_item_splitter_default2'>
          <Card2 text_title='NEW COLLECTION ARRIVED' />
          <Card2 text_title='NEW COLLECTION ARRIVED' />
        </ItemSplitter>
        <ItemSplitter classes='grid_item_splitter_default4'>
          {mid &&
            mid.map((el) => (
              <CardProduct2
                key={el.title}
                link_url='/category/women'
                text_title={el.title.toUpperCase()}
                text_price={el.price + "" + "$"}
                text_category={el.category.toUpperCase()}
                text_size='text-base'
                priority={true}
              />
            ))}
          {/* <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          /> */}
        </ItemSplitter>
        <Card3
          text_title='NEW STUFF'
          img_url={"/f10.webp"}
        />
        <ItemSplitter classes='grid_item_splitter_default4'>
          {bottom &&
            bottom.map((el) => (
              <CardProduct2
                key={el.title}
                link_url='/category/men'
                text_title={el.title.toUpperCase()}
                text_price={el.price + "" + "$"}
                text_category={el.category.toUpperCase()}
                text_size='text-base'
                priority={true}
              />
            ))}
          {/* <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          /> */}
        </ItemSplitter>
        <ItemSplitter classes='grid_item_splitter_default2'>
          <Card2 text_title='NEW COLLECTION ARRIVED' />
          <Card2 text_title='NEW COLLECTION ARRIVED' />
        </ItemSplitter>
        {/* <ItemSplitter classes='grid_item_splitter_default4'>
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
        </ItemSplitter> */}
      </Main>
      <Footer classes='footer_default'>
        <div>FOOTER</div>
      </Footer>
    </MainWrapperDiv>
  );
}
async function myFetch() {
  let files = [];
  const women = await axios.get(
    "https://fakestoreapi.com/products/category/women%27s%20clothing?limit=4"
  );
  const men = await axios.get(
    "https://fakestoreapi.com/products/category/men%27s%20clothing?limit=4"
  );

  files.push(women.data);
  files.push(men.data);

  return files;
}
export async function getStaticProps() {
  let products = [];
  // const {data} = await axios.get(
  //   "https://fakestoreapi.com/products/category/w/categoryomen%27s%20clothing?limit=4"
  // );
  const data = await myFetch();
  // /category"men's clothing",
  // "w/categoryomen's clothing"

  if (!data) {
    return {
      redirect: {
        destination: "/",
      },
    };
  }

  return {
    props: {
      top: data[0],
      mid: data[0],
      bottom: data[1],
    },
  };
}
