import Head from "next/head";
import Image from "next/image";
import {MainWrapperDiv} from "./../components/MainResponsive/MainWrapperBox";
import {HeaderMain} from "./../components/Header/HeaderMain";
import Header from "../components/Elements/GridItem";
import Main from "../components/Elements/GridItem";
import Footer from "../components/Elements/GridItem";
import Card1 from "./../components/Cards/Card1";
import ItemSplitter from "../components/Elements/GridItem";
import {Card2} from "./../components/Cards/Card2";
import {Card3} from "./../components/Cards/Card3";
import {CardProduct} from "./../components/Cards/CardProduct";
import {CardProduct2} from "./../components/Cards/CardProduct2";
import {CardVideo} from "../components/Cards/CardVideo";

export default function Home() {
  return (
    <MainWrapperDiv>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1.0'></meta>
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Mansalva&family=Rajdhani:wght@600&family=Roboto&display=swap'
          rel='stylesheet'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header classes='header_default_div'>
        <HeaderMain />
      </Header>
      <Main classes='main_default_style'>
        <CardVideo video_default='w-full mb-4' />
        <ItemSplitter classes='grid_item_splitter_default4'>
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
        </ItemSplitter>
        <Card3
          text_wrapper='relative text-center -top-16'
          text_bg='bg-pink'
        />
        <ItemSplitter classes='grid_item_splitter_default4'>
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
          <Card1 link_url='#' text='SUMMER VIBES' />
        </ItemSplitter>
        <ItemSplitter classes='grid_item_splitter_default2'>
          <Card2 text_title='NEW COLLECTION ARRIVED' />
          <Card2 text_title='NEW COLLECTION ARRIVED' />
        </ItemSplitter>
        <Card2 text_title='NEW COLLECTION ARRIVED' />
        <Card3 text_title='NEW STUFF' />
        <ItemSplitter classes='grid_item_splitter_default4'>
          {/* <div className='grid xl:grid-cols-4 md:grid-cols-2 sm:grid-cols-1 gap-x-2'> */}
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          <CardProduct2
            text_title='PRODUCT TITLE'
            text_price='22 €'
            text_category='SHOES'
            text_size='text-base'
          />
          {/* </div> */}
        </ItemSplitter>
        <CardProduct
          text_price='22 €'
          text_category='SHOES'
        />
        <CardProduct2
          text_title='PRODUCT TITLE'
          text_price='22 €'
          text_category='SHOES'
          text_size='text-lg'
        />{" "}
        {/* <CardVideo /> */}
        {/* </div> */}
      </Main>
      <Footer classes='footer_default'>
        <div>FOOTER</div>
      </Footer>
    </MainWrapperDiv>
  );
}
